steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0000390214-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0000390214-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0000390214-flow4
    integrationFlowName: S0000390214-flow4
    packageId: CICD
    filePath: S0000390214-flow4.zip